version: "3.8"

services:
  frontend:
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://your-backend-api-url.com/api
    restart: always
    build:
      args:
        - NODE_ENV=production

  backend:
    restart: always
    environment:
      - FLASK_ENV=production
