version: "3.8"

services:
  frontend:
    command: npm run dev
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"

  backend:
    command: python -m flask run --host=0.0.0.0 --port=5000
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
